### 测试后台
GET http://localhost:3000/tests



### 测试后台
POST http://localhost:3000/tests
Content-Type: application/json

{
  "name":"张三",
  "age":15
}


###  登录管理员
POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"admin",
  "password":"admin"
}

### 测试鉴权
GET http://localhost:3000/who



###  登录 辅导员
### db.counselors.insert({"counselorId":"counselor",password:"123456"})
POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"counselorId",
  "password":"123456"
}

###  登录 学生
POST http://localhost:3000/login
Content-Type: application/json

{
  "username":"20181506210411",
  "password":"asdasdasd"
}



### 修改密码
POST http://localhost:3000/changePassword
Content-Type: application/json

{
  "username":"counselor",
  "pre":"123456",
  "next":"counselor"
}

###  创建学生
POST http://localhost:3000/students
Content-Type: application/json

{
  "stuId":"20181506210411",
  "password":"123456",
  "name":"张三",
  "age":15,
  "position":{
    "academy":"计算机院",
    "major":"计算机专业",
    "_class":"18计科4班"
  },
  "phone":17530111012,
  "actions":[
    {
    "name":"三好学生",
    "grade":"校级"
   },{
    "name":"优秀班干部",
    "grade":"校级"
   }
  ]
}