### 学生申请 award
POST http://localhost:3000/students/createAward
Content-Type: application/json

{
  "applyType":"个人奖学金",
  "applyName":"优秀班干部",
  "applyLevel":"校级",
  "applyMain":"学习好就是吊777"
} 

### 学生申请修改成绩
POST  http://localhost:3000/students/changeGrade
Content-Type: application/json

{
  "grade_id":"620b6a34e651b3a31fcfc36a",
  "newGrade":"70"
}

### 学生查询自己的成绩
GET  http://localhost:3000/students/getAllGrade?stuid=20181506210411


### 学生查看自己的奖学金申请情况
GET  http://localhost:3000/students/findsAwardCondition

### 学生查看自己成绩请情况
GET  http://localhost:3000/students/findGradeApply


### 学生查看自己的所有申请
GET http://localhost:3000/students/findAllApply

### 查看自己的所有成绩
GET http://localhost:3000/students/findAllGrades


### 查看自己的奖惩
GET http://localhost:3000/students/findAllActions

### 修改自己的基本信息
POST http://localhost:3000/students/upDateInfo
Content-Type: application/json

{
  "name":"backgron",
  "age":19,
  "position":{
    "academy":"计算机学院",
    "major":"计算机专业",
    "_class":"18计科4班"
  },
  "phone":175394432
}

//   db.students.find({"stuId":"20181506210411"})
//   db.students.update({"stuId":"20181506210411"},{$set:{awards:[]}})
//   db.awards.drop()

###  学生自己修改密码
POST http://localhost:3000/students/changeStuPassword
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"asdasdasd"
}
### 测试鉴权
GET http://localhost:3000/who

